# github:
#   prebuilds:
#     master: false
#     branches: false
#     pullRequests: false
#     addCheck: false
#     addComment: false
#     addLabel: prebuild-in-gitpod

# NG_CLI_ANALYTICS=ci

tasks:
  - before: export NG_CLI_ANALYTICS=ci
            npm i -g @angular/cli &&
            ng analytics off
    init: ng analytics off &&
          npm install
    command: >
      npm i -g json-server &&
      json-server --watch db.json --host 0.0.0.0 --disable-host-check
  - command: >
      gp await-port 3000 &&
      npm i -g nodemon &&
      nodemon server.js --host 0.0.0.0 --disable-host-check
  - command: >
      gp await-port 8000 &&
      ng serve --host 0.0.0.0 --disable-host-check

ports:
  - port: 3000
    onOpen: ignore
  - port: 8000
    onOpen: ignore
  - port: 4200
    onOpen: open-preview
