github:
  prebuilds:
    master: false
    branches: false
    pullRequests: false
    addCheck: false
    addComment: false
    addLabel: prebuild-in-gitpod

tasks:
  - before: export NG_CLI_ANALYTICS=ci &&
            npm i -g @angular/cli &&
            ng analytics off
    init: ng analytics off &&
          npm install && npm run build
    command: npm run start
    # command: >
    #   ng serve --host 0.0.0.0 --disable-host-check

ports:
  - port: 4200
    onOpen: open-browser
